config/routes.rb
Dare::Application.routes.draw do

  root :to => "challenges#index"

  match '/auth/:provider/callback', :to => 'users#auth'
  match '/auth/failure', :to => "users#failure", :as => "failure"
  match '/logout', :to => "users#logout", :as => "logout"

  resources :users do
    get :fb_friends, :on => :collection,
      :constraints => { :format => /js|json/ }, :as => "fb_friends"
  end

  resources :challenges do
    resources :proofs, :to => "challenges/proofs"
    get "accept"
    get "reject"
  end
  

end

app/models/proof.rb
# require 'app/uploaders/proof_uploader'

class Proof
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  belongs_to :challenge
  belongs_to :user

  field :proof, type: Integer, default: 0
  field :comment, type: String

  embeds_many :proof_votes
  
  default_scope order_by([:created_at,:asc])

  mount_uploader :photo, ProofUploader
end

app/controllers/challenges/proofs_controller.rb
class Challenges::ProofsController < ApplicationController

	def create
		id = params[:challenge_id].match(/\d+\w+/).to_s
		@challenge = Challenge.find(id)

		@proof = Proof.new params[:proof]
		@proof.challenge = @challenge
		@proof.user = current_user

		if @proof.valid?
			@proof.save
			
			#TODO:Image ONLY!!!
			@challenge.proofs_count = @challenge.proofs_count+1

			return redirect_to challenge_path(@challenge)
		end

		respond_with(@challenge) do |f|
			f.html{ render "challenges/show" }
		end
	end


	def destroy
		@proof = Proof.find(params[:id])
		if @proof.user == current_user
			@proof.destroy

			challenge = @proof.challenge
			challenge.proofs_count = challenge.proofs_count-1
			challenge.save
		end

		redirect_to challenge_path(@proof.challenge)
	end

end

app/views/proofs/_form.html.haml
.proof_form
	%hr/

	= form_for [@challenge,@proof] do |f|
		-if f.object.errors.any?
			%ul.form_errors
				- f.object.errors.full_messages.each do |e|
					%li=e

		.user
			.image=image_tag current_user.image(:square), width:20
			.name=current_user
		
		.comment=f.text_area :comment, rows: 3

		.photo
			=f.file_field :photo

		=f.submit

app/views/proofs/_proof.html.haml
.proof{class: proof.photo? ? "with_photo": ""}
	

	.user
		.image=image_tag proof.user.image(:square)
		.name
			=link_to proof.user, user_path(proof.user)
		-unless proof.created_at.nil?
			.created_at=time_ago_in_words proof.created_at

	- unless proof.comment.nil?
		.comment=proof.comment

	- if proof.photo?
		.photo=image_tag proof.photo.thumb

	- if signed_in? and proof.user == current_user
		=link_to t("remove"), challenge_proof_path(proof.challenge,proof), :method => :delete