config/routes.rb
Dare::Application.routes.draw do

  root :to => "challenges#index"

  match '/auth/:provider/callback', :to => 'users#auth'
  match '/auth/failure', :to => "users#failure", :as => "failure"
  match '/logout', :to => "users#logout", :as => "logout"

  resources :users do
    get :fb_friends, :on => :collection,
      :constraints => { :format => /js|json/ }, :as => "fb_friends"
  end

  resources :challenges do
    resources :proofs, :to => "challenges/proofs"
    get "accept"
    get "reject"
  end
  

end

app/models/challenge.rb
class Challenge
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title
  field :description
  field :punishment
  field :reward

  field :public, type: Integer, default: 0
  field :deleted, type: Integer, default: 0
  field :deadline, type: DateTime
  field :proofs_count, type: Integer, default: 0

  validates_presence_of :from
  validates_presence_of :title
  validates_presence_of :deadline

  belongs_to :from, class_name: "User"

  embeds_many :invited_list, class_name: "FbUser"
  embeds_many :accepted_list, class_name: "FbUser"
  embeds_many :rejected_list, class_name: "FbUser"

  has_many :proofs

  accepts_nested_attributes_for :invited_list
  accepts_nested_attributes_for :accepted_list

  attr_accessor :friend_search

  validate do |ch|
    # ch.must_not_invite_himself
    ch.must_have_users_if_private
    ch.must_be_punishment_or_reward
    ch.must_be_in_future
  end

  def to_s
  	"#{self.title}"
  end

  def to_param
  	"#{self.id}-#{self.title}".parameterize
  end

  # Challenge must have punishment or reward
  def must_be_punishment_or_reward
  	if (punishment.nil? or punishment.to_s.strip == "") and
  		(reward.nil? or reward.to_s.strip == "")
  			errors.add(:base, "Challenge must have punishment and/or reward")
  	end  
  end

  # Challange deadline must be set in feature
  def must_be_in_future
	if deadline.nil? || deadline < DateTime.now
		errors.add(:deadline, "must be set in feature")
  	end
  end

  def must_have_users_if_private
  	if private? and (invited_list.nil? || invited_list.empty?)
  		errors.add(:invited_list, "must include at least one your friends")
  	end
  end

  def must_not_invite_himself
    if not(invited_list.nil?) and not(invited_list.empty?)
      in_invlist = invited_list.where({fb_uid:fb_uid}).first
      unless in_invlist.nil?
        errors.add(:invited_list,"You can't invite yourself!")
      end
    end
  end

  # You must set at least one FB user if its not for all
  def must_have_to_fb_uids
  	if not(for_all?) and (self.to_fb_uids.nil? or self.to_fb_uids.empty?)
  		errors.add(:base,"If the challenge is not for everybody. Then you must set Facebook users.")
  	end
  end

  def public?
  	self.public == 1
  end

  def private?
  	not public?
  end

  default_scope order_by([:updated_at,:desc])

  scope :public, where(deleted: 0)

  scope :all, ->(){
    public
  }
  scope :page, ->(page=1, per_page=12){
    page=0 if page < 0 # Start at page=1

    per_page = per_page + 1 # check!
    skip = (page*per_page)-page
    skip = 0 if skip < 0
    limit(per_page).skip(skip)
  }

  # Find all challenges where user is involved
  scope :from, ->(user){
    if user.class == User
      any_of({ from_id: user.id },
        {:"invited_list.fb_uid" => user.fb_uid},
        {:"accepted_list.fb_uid" => user.fb_uid},
        {:"rejected_list.fb_uid" => user.fb_uid}
      )
    elsif user.class == FbUser
      any_of(
        {:"invited_list.fb_uid" => user.fb_uid},
        {:"accepted_list.fb_uid" => user.fb_uid},
        {:"rejected_list.fb_uid" => user.fb_uid}
      )
    end
  }

  scope :accepted, ->(user){
    any_of(
        {:"accepted_list.fb_uid" => user.fb_uid}
      )
  }

  scope :invited, ->(user){
    any_of(
        {:"invited_list.fb_uid" => user.fb_uid}
      )
  }

  scope :rejected, ->(user){
    any_of(
        {:"rejected_list.fb_uid" => user.fb_uid}
    )    
  }

  def invited? user
    #invited_list.where(:"fb_uid"=>user.fb_uid).first
    invited_list.to_a.map(&:fb_uid).include? user.fb_uid
  end

  def rejected? user
    #rejected_list.where(:"fb_uid"=>user.fb_uid).first
    rejected_list.to_a.map(&:fb_uid).include? user.fb_uid
  end

  def accepted? user
    #accepted_list.where(:"fb_uid"=>user.fb_uid).first
    accepted_list.to_a.map(&:fb_uid).include? user.fb_uid
  end

  def owner? user
    from == user
  end

  def can_accept? user
    return false if expired? or owner?(user)

    if public?
      not(accepted?(user))
    elsif private?
      if invited?(user)
        not(accepted?(user))
      else
        false
      end
    else
      false
    end
  end

  def can_reject? user
    return false if expired? or owner? user

    if public?
      accepted?(user)
    elsif private?
      if invited?(user)
        not(rejected?(user))
      else
        false
      end
    else
      false
    end
  end

  def accept! user
    if can_accept? user
      fb_user = user.to_fbuser
      fb_user.created_at = DateTime.now

      rejected_list.destroy_all(fb_uid: fb_user.fb_uid)
      accepted_list << fb_user
      save
    end
  end

  def reject! user
    if can_reject? user
      fb_user = user.to_fbuser
      fb_user.created_at = DateTime.now

      accepted_list.destroy_all(fb_uid: fb_user.fb_uid)
      rejected_list << fb_user
      save
    end
  end

  def can_proof? user
    accepted?(user) or from==user
  end

  def one_on_one?
    not(public?) and (
      not(invited_list.nil?) and invited_list.size == 1)
  end

  def expired?
    DateTime.strptime(deadline.to_s) < DateTime.now
  end

  def has_image_proofs?
    proofs.where(:"photo.ne" => nil).last
  end

  def statuses
    out = []

    out << :expired if expired?
    out << :ongoing if not(expired?)
    out << :public if public?
    out << :private if not(public?)
    out << :one_on_one if one_on_one?
    out << :with_proofs if has_image_proofs?

    out
  end

  def possible_actions

  end

=begin

  # Order by updated_at
  default_scope order_by([:updated_at,:desc])

  # Restrict to user
  scope :by, ->(user){
  	where(:to_fb_uids => user.fb_uid)
  }

  scope :public, where(deleted: 0)
  
  scope :with_status, ->(status_flag) {
  	public.where(status:status_flag.to_s)
  }

  scope :all, ->(){
  	public # 1toN
  }

  scope :accepted, ->(){
  	with_status(:accepted)
  }
=end

end

app/controllers/challenges/proofs_controller.rb
class Challenges::ProofsController < ApplicationController

	def create
		id = params[:challenge_id].match(/\d+\w+/).to_s
		@challenge = Challenge.find(id)

		@proof = Proof.new params[:proof]
		@proof.challenge = @challenge
		@proof.user = current_user

		if @proof.valid?
			@proof.save
			
			#TODO:Image ONLY!!!
			@challenge.proofs_count = @challenge.proofs_count+1

			return redirect_to challenge_path(@challenge)
		end

		respond_with(@challenge) do |f|
			f.html{ render "challenges/show" }
		end
	end


	def destroy
		@proof = Proof.find(params[:id])
		if @proof.user == current_user
			@proof.destroy

			challenge = @proof.challenge
			challenge.proofs_count = challenge.proofs_count-1
			challenge.save
		end

		redirect_to challenge_path(@proof.challenge)
	end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
	include ActionView::Helpers::DateHelper

	respond_to :html, :json, :js

	before_filter :find_challenge, :only => [
		:edit, :show, :destroy, :update, :accept, :reject]

	def find_challenge
		begin
			f_id = params[:id]
			f_id = params[:challenge_id] if f_id.nil?
			id = f_id.match(/\d+\w+/).to_s
			@challenge = Challenge.find(id)

			if @challenge.deleted?
				flash[:error] = t("challenge_deleted")
				return redirect_to root_url
			end
		rescue
			flash[:error] = t("challenge_missing")
			return redirect_to root_url
		end
	end

	def index
		@types = %w(all mine)
		@type = params[:type] || "all"
		@mode = params[:mode]

		@page = params[:page].to_i <= 0 ? 0 : params[:page].to_i
		@per_page = params[:per_page].to_i <= 0 ? 12 : params[:per_page].to_i

		@type = @types.first unless @types.include?(@type)
		if @type =~ /mine/i
			if @mode =~ /accepted|invited|rejected/
				@challenges = Challenge.all.send Regexp.last_match.to_s.to_sym, current_user
			else
				@challenges = Challenge.all.from current_user
			end
		else
			@challenges = Challenge.all
		end
		
		@challenges = @challenges.page(@page,@per_page)

		@challenges = ChallengeDecorator.decorate(@challenges)
		
		respond_with(@challenges)
	end


	#TODO: Improve!!!
	def show
		@proof = Proof.new(user: current_user)
		@challenge = ChallengeDecorator.new(@challenge)
	end

	def new
		@challenge = Challenge.new(from: current_user,
			deadline: DateTime.now+2.days)
	end

	def create
		@challenge = Challenge.new params[:challenge]
		@challenge.from = current_user

		if @challenge.valid?
			@challenge.save
			flash[:notice]=t("challenge_created")
			return redirect_to challenge_path(@challenge)
		end

		render :edit
	end

	def update
		if @challenge.update_attributes(params[:challenge])
			flash[:notice]=t("challenge_updated")
			@challenge.save
		end

		render :edit
	end

	def edit
	end

	def accept
		if @challenge.accept! current_user
			flash[:notice]=t("challenge_accepted",
				deadline:
					distance_of_time_in_words_to_now(@challenge.deadline))
		end

		return redirect_to challenge_path(@challenge)
	end

	def reject
		if @challenge.reject! current_user
			flash[:notice]=t("challenge_rejected", challenge:@challenge)
		end

		return redirect_to challenge_path(@challenge)
	end
end

app/helpers/challenges_helper.rb
module ChallengesHelper

	def can_accept? user=nil
		@challenge.can_accept?(user || current_user)
	end

	def can_reject? user=nil
		@challenge.can_reject?(user || current_user)
	end

	def owner? user=nil
		user ||= current_user
		@challenge.from == user
	end

	def can_proof? user=nil
		@challenge.can_proof?(user || current_user)
	end

	def challenge_proofs &block
		if @challenge.proofs.size > 0
			content_tag :proofs, yield(block)
		end
	end

	def proof? &block
		user ||= current_user

		if @challenge.can_proof? user
			yield(block)
		end

		#TODO: Add reason why not!!!
	end

	def has_next=(value=false)
		@has_next ||= value
	end

	def has_next?
		@has_next || false
	end
	
	def has_prev=(value=false)
		@has_prev ||= value
	end

	def has_prev?
		@has_prev || false
	end

	def render_challenges collection
		if collection.empty?
			return content_tag :div, class: "empty_challenges_list" do
				t("empty_challenges_list")
			end
		end

		# return collection.count
		size = collection.count
		@has_next=true if size >= @per_page+1
		@has_prev=true if @page > 0

		# LAST RECORD?
		# render collection
		render collection[0..(@per_page-1)]
		
	end

	def render_challenges_paging
		out = []

		if has_prev?
			out << content_tag(:div, class: "prev") do
				link_to(t("page_prev"), challenges_path(
					:type => @type,
					:mode => @mode,
					:page => @page-1,
					:per_page => @per_page
				),class: "page_prev")
			end
		end

		if has_next?
			out << content_tag(:div, class: "next") do
				link_to(t("page_next"), challenges_path(
					:type => @type,
					:mode => @mode,
					:page => @page+1,
					:per_page => @per_page
				),class: "page_next")
			end
		end

		raw out.join(&:+)
	end
end

app/views/challenges/_challenge.html.haml
- statuses= challenge.statuses
.challenge{class: statuses}

	%h3=link_to challenge, challenge_path(challenge)

	.images
		=image_tag "versus.png", class: "versus"

		- if (statuses.include? :with_proofs)
			=link_to challenge_path(challenge) do
				=image_tag challenge.has_image_proofs?.photo.thumb, :class => "proof"

		.user_a
			=link_to challenge_path(challenge) do
				=image_tag challenge.from.image(:square)
				%span.name=challenge.from.to_s.split(" ").first

		- if statuses.include? :one_on_one
			.user_b
				=link_to challenge_path(challenge) do
					=image_tag challenge.invited_list.first.image(:square)
					%span.name=challenge.invited_list.first.to_s.split(" ").first

		- else
			.user_b
				=link_to challenge_path(challenge) do
					- if challenge.accepted_list.empty?
						- if not challenge.invited_list.first.nil?
							=image_tag challenge.invited_list.first.image(:square)
							%span.name=challenge.invited_list.first.to_s.split(" ").first
					- else
						=image_tag challenge.accepted_list.first.image(:square)
						%span.name=challenge.accepted_list.first.to_s.split(" ").first

	= challenge.perticipants 7

	= challenge.deadline

	= challenge.tools

	-#
		- if signed_in? 
			.challenge_tools
				- if challenge.can_accept?(current_user)
					=link_to t("accept"), [challenge,:accept], class: "accept"
				
				- if challenge.can_reject?(current_user)
					=link_to t("reject"), [challenge,:reject], class: "reject"

app/views/challenges/_form.html.haml
- content_for :head do
	=javascript_include_tag fb_friends_users_url(:format => "js")

.challenge_form
	.twelve.columns
		= form_for @challenge do |f|

			.users_pick
				.users_chb_wrap.challenge
					=image_tag "versus.png", {class: "versus"}

					.img_wrap.user_a
						=fb_image_tag f.object.from
					.img_wrap.user_b
						%span.number=0
						=image_tag "default_profile.jpg"


			.form_fields
				-if f.object.errors.any?
					%ul.form_errors
						- f.object.errors.full_messages.each do |e|
							%li=e

				%label{for: "challenge_title"}=t("challenge_title")
				= f.text_field :title

				.invited_list
					%label.fb
						=t "invited_list"
						%span.grey=t "type_friend_name"
					= f.text_field :friend_search

					%ul
						= f.fields_for :invited_list do |sf|
							%li{:class=>"fb_friend", "data-fb_uid" => sf.object.fb_uid, "data-name" => sf.object.name}
								= image_tag "http://graph.facebook.com/#{sf.object.fb_uid}/picture?type=square"
								.labl
									%span.name=sf.object.name
									%a{href:"#remove", class:"remove"}="Remove"
								= sf.hidden_field :fb_uid, class: "i_fb_uid"
								= sf.hidden_field :name, class: "i_name"




					

				%label{for: "challenge_description"}=t("challenge_description")
				= f.text_area :description, {rows: 2}

				.reward_punishment_split
					.reward_wrap
						%label{for: "challenge_reward"}=t("challenge_reward")
						= f.text_area :reward, {rows: 2}

					.punishment_wrap
						%label{for: "challenge_punishment"}=t("challenge_punishment")
						= f.text_area :punishment, {rows: 2}


				%label{for: "challenge_deadline"}=t("challenge_deadline")
				= f.text_field :deadline


				.challenge_public
					= f.check_box :public
					%label{for: "challenge_public"}
						=t("challenge_public")
						%span.grey=t("if_public")

				= f.submit

app/views/challenges/edit.html.haml
%h2=page_title t("editing_challenge",:challenge => @challenge)

= render "form"

app/views/challenges/index.html.haml
.top_tools
	.twelve.columns
		- if signed_in?
			=link_to t(".add"), new_challenge_path, {class: "add2"}

		%ul#filter
			%li=link_to t("all"), challenges_path

			- if signed_in?
				%li=link_to t("mine"), challenges_path(:type => "mine")

				- if params[:type] == "mine"
					(
					=link_to t("invited"), challenges_path(:type => "mine", :mode => "invited")
					|
					=link_to t("accepted"), challenges_path(:type => "mine", :mode => "accepted")
					|
					=link_to t("rejected"), challenges_path(:type => "mine", :mode => "rejected")
					)
	- if signed_in?
		.four.columns
			=link_to t(".add"), new_challenge_path, remote: !true, class: "add"

.sixteen.columns
	#challenges
		=render_challenges @challenges

	#challenges_paging
		= render_challenges_paging

app/views/challenges/new.html.haml
%h2=page_title t("new_challenge")

= render "form"

app/views/challenges/new.js.erb
var challenge_form = $("<%= j render('form') %>");

challenge_form.hide();

challenge_form.appendTo($("body .content")).dialog({
	modal:true,
	width:"50%",
	title:"<%= t('challenges.index.add') %>",
	draggable:false,
	close:function(event,ui){

	}
});

jQuery.getScript("/users/fb_friends.js",function(){
	$("body #new_challenge").ChallengeFormPlugin();
});

app/views/challenges/show.html.haml
%h2=page_title @challenge

= @challenge.tools

.challenge_form.challenge_show

	.four.columns
		=t(@challenge.public? ? "challenge_public" : "challenge_private")
		= @challenge.deadline_raw
		= @challenge.created
		= @challenge.perticipants 5

	.twelve.columns
		.from
			= image_tag @challenge.from.image(:square)
			= @challenge.from

		- if @challenge.description.present?
			.description=@challenge.description
	
		- challenge_proofs do
			%h3=t("proofs_and_comments")
			.proofs_list= render :partial => "proofs/proof", :collection => @challenge.proofs

		- proof? do
			= render "proofs/form"