config/routes.rb
Dare::Application.routes.draw do

  root :to => "challenges#index"

  match '/auth/:provider/callback', :to => 'users#auth'
  match '/auth/failure', :to => "users#failure", :as => "failure"
  match '/logout', :to => "users#logout", :as => "logout"

  resources :users do
    get :fb_friends, :on => :collection,
      :constraints => { :format => /js|json/ }, :as => "fb_friends"
  end

  resources :challenges do
    resources :proofs, :to => "challenges/proofs"
    get "accept"
    get "reject"
  end
  

end

app/views/layouts/_header.html.haml
-# todo move to CSS
:css
	.region a.active{ font-weight:bold; color:red; }

.nine.columns
	%h1.remove-bottom
		=link_to root_path do
			=raw "<span>2</span>DA.RE"
			-# =raw "<span class=\"mission_statement\">#{t("mission_statement")}</span>"
	-# %h5=t 'challenge_accepted'

.seven.columns.facebook
	- unless signed_in?
		=link_to t("login_with_facebook"), login_path, {class: 'auth'}
	- else
		=link_to current_user, user_path(current_user)
		\/
		%a(href="#reload-location")
			%span.address=current_user.address	
		\/
		=current_user.locale

		\/
		=link_to t("logout"), logout_path, {class: 'auth'}

app/views/layouts/application.html.haml
!!!
%head
	%title=page_title
	= stylesheet_link_tag "application", :media => "all"
	= javascript_include_tag "application"
	= csrf_meta_tags

	- if content_for?(:head)
		= yield :head

%body{rails_location}
	.container
		#header=render "layouts/header"
		
		%hr/

		- if not(flash[:error].nil?) or not(flash[:notice].nil?)
			.messages
				- unless flash[:error].nil?
					.error=flash[:error]
				- unless flash[:notice].nil?
					.notice=flash[:notice]


		.content
			= yield

app/views/layouts/beta.html.haml
!!!
%html
	%head
		%title Ready 2da.re?
		= stylesheet_link_tag "application", :media => "all"
		= javascript_include_tag "application"

		:css
			.main{ margin:0 auto; text-align:center; margin-top:30%; max-width:500px;}
			.main p.mission{ font-size: 30px; margin-bottom:0px; text-transform:uppercase; }
			.main p.details{ border-top:1px solid black; border-bottom:1px solid black; }
			p{ margin:0px; padding:0px; padding:3px; }
	%body
		.main
			%p.mission
				Ready
				%span.red 2da.re
				your friends?
			%p.details Soon. Just hold on or come back!